---
title: "Graficos"
author: "Curso de Estadística Descriptiva"
date: "22/12/2018"
output:
  html_document: default
  pdf_document: default
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Gráficos con la función `plot`

```{r primer_plot, fig.cap="Gráfico básico explicando el uso del plot", fig.align='center'}
x = c(2,6,4,9,-1)
y = c(1,8,4,-2,4)
plot(x,y)
```

Si no incorporamos vector `y`, `R` nos va a tomar el parámetro `x` como si fuese el vector de datos `y` : `plot(1:n, x)

```{r}
plot(2^(1:6))
```

Si queremos representar una función $f(x)$:

```{r}
f <- function(x){ sqrt(x) }
plot(f)
```

## Parámetros

```{r, echo=FALSE, fig.align='center'}
n = 1:20
fib = (1/sqrt(5))*((1+sqrt(5))/2)^n - (1/sqrt(5))*((1-sqrt(5))/2)^n
fib
par(mfrow = c(1,2))
plot(fib, xlab = "n", ylab = expression(F[n]),
     main = "Sucesión de Fibonacci", pch = 21, cex = 2,
     col = "powderblue", bg = "orchid", log = "xy")

plot(fib, xlab = "n", ylab = expression(F[n]),
     main = "Sucesión de Fibonacci", pch = 21, cex = 2,
     col = "powderblue", bg = "orchid", log = "y")
par(mfrow = c(1,1))
```


```{r}
plot(n, fib, pch = 21, col = "red", bg = "yellow", cex = 1.2, 
     main = "Fibonacci",
     type = "o", lty = "dashed", lwd = 2, 
     xlim = c(1,10), ylim = c(1, 100),
     xaxp = c(1,10,3), yaxp = c(0,100, 10))
```

## Cómo añadir elementos a un gráfico
```{r}
f <- function(x){
  x^2 -2*x + sqrt(abs(x))
}
plot(f, xlim = c(-3,3))
points(0,0, pch = 19)
points(-3:3, (-3:3)^2, col = "blue")
abline(2,3, lty = "dashed", col = "red")
abline(v = 2, lty = "dotted", col = "green")
abline(h = 5, lty = "dotdash", col = "gray")
```

```{r}
f <- function(x){x^2}
plot(f, xlim = c(-3,3), col = "red", lwd = 2, ylab = expression(y^2), xlab = "x")
abline(h=0:9, v = -3:3, lty="dotted", col = "grey")
```

```{r}
plot(tan, xlim = c(-pi, pi), ylim = c(-5,5))
abline(v = c(-pi/2, pi/2), col = "red")
```

```{r}
plot(0,0)
text(0,0, labels = "debajo", pos = 1)
text(0,0, labels = "izquierda", pos = 2)
text(0,0, labels = "arriba", pos = 3)
text(0,0, labels = "derecha", pos = 4)
points(0,1)
text(0,1, labels = "centro")
```


```{r}
f <- function(x){x^2}
plot(f, xlim = c(-3,3), ylim = c(-10,10))
points(-3:3, f(-3:3), pch = 19)
lines(-3:3, f(-3:3), lwd = 2, lty = "dotted", col = "red")
curve(x^3, lty = "dashed", col = "blue", add = TRUE)
curve(x^4, lty = "dashed", col = "orangered", add=TRUE)
legend("bottomright", 
       legend = c(expression(x^2), expression(x^3), expression(x^4)), 
       lwd = 2, 
       col = c("red", "blue", "orangered"), 
       lty = c("dotted", "dashed", "dashed")
       )
```

```{r}
iterations = training_evolution_prueba3$Iterations
map = training_evolution_prueba3$`mAP @ 0.5 (%)`
precision = training_evolution_prueba3$`Precision (%)`
recall = training_evolution_prueba3$`Recall (%)`
f1score = training_evolution_prueba3$`F-score (%)`

png(filename=paste("C:/Users/mudar/Universidad de Alcala/JesusMudarra-MUII - Documentos/General/results/mAP_iteraciones_YOLOv4/prueba1/map.png",sep=""), width=5, height=5,units="in", res=300, pointsize=12)

plot(iterations,map, xlab = "Iteration number", ylab = "mAP (%)",type = "o", lty = "solid", lwd = 2, col = "mediumpurple4", ylim = c(25,65), pch=20, cex = 1.5, xaxt = "none", yaxt = "none")
axis(1, seq(0,20000, 2000),las=1, font=2,cex.axis=0.8)
axis(2, seq(0,65,5),las=2, font=2)

abline(h=seq(0,65,5), v=seq(0,20000, 2000), lty=3, col="lightgray")

abline(v = 10000, lty = "dotted", col = "seagreen")
abline(h = 60.97, lty = "dotdash", col = "seagreen")


dev.off()


plot(iterations,precision, xlab = "Iteration number", ylab = "Precision (%)",type = "o", lty = "solid", lwd = 2, col = "goldenrod4", ylim = c(25,65), pch=17, cex = 1.5, xaxt = "none", yaxt = "none")
axis(1, seq(0,20000, 2000),las=1, font=2,cex.axis=0.8)
axis(2, seq(0,65,5),las=2, font=2)

abline(h=seq(0,65,5), v=seq(0,20000, 2000), lty=3, col="lightgray")

abline(v = 10000, lty = "dotted", col = "seagreen")
abline(h = 47.26, lty = "dotdash", col = "seagreen")



plot(iterations,recall, xlab = "Iteration number", ylab = "Recall (%)",type = "o", lty = "solid", lwd = 2, col = "chocolate4", ylim = c(25,65), pch=18, cex = 1.5, xaxt = "none", yaxt = "none")
axis(1, seq(0,20000, 2000),las=1, font=2,cex.axis=0.8)
axis(2, seq(0,65,5),las=2, font=2)

abline(h=seq(0,65,5), v=seq(0,20000, 2000), lty=3, col="lightgray")

abline(v = 10000, lty = "dotted", col = "seagreen")
abline(h = 55.81, lty = "dotdash", col = "seagreen")




plot(iterations,f1score, xlab = "Iteration number", ylab = "F1-score (%)",type = "o", lty = "solid", lwd = 2, col = "darkslategray", ylim = c(25,65), pch=15, cex = 1.5, xaxt = "none", yaxt = "none")
axis(1, seq(0,20000, 2000),las=1, font=2,cex.axis=0.8)
axis(2, seq(0,65,5),las=2, font=2)

abline(h=seq(0,65,5), v=seq(0,20000, 2000), lty=3, col="lightgray")

abline(v = 10000, lty = "dotted", col = "seagreen")
abline(h = 51.18, lty = "dotdash", col = "seagreen")


```
```{r}
iterations = training_evolution_prueba1$Iterations
map = training_evolution_prueba1$`mAP @ 0.5 (%)`
precision = training_evolution_prueba1$`Precision (%)`
recall = training_evolution_prueba1$`Recall (%)`
f1score = training_evolution_prueba1$`F-score (%)`



plot(iterations,map, xlab = "Iteration number", ylab = "mAP (%)",type = "o", lty = "solid", lwd = 2, col = "mediumpurple4", ylim = c(25,70), pch=20, cex = 1.5, xaxt = "none", yaxt = "none")
axis(1, seq(0,8000, 1000),las=1, font=2,cex.axis=0.8)
axis(2, seq(0,70,5),las=2, font=2)

abline(h=seq(0,70,5), v=seq(0,20000, 1000), lty=3, col="lightgray")

abline(v = 2000, lty = "dotted", col = "seagreen")
abline(h = 66.25, lty = "dotdash", col = "seagreen")



plot(iterations,precision, xlab = "Iteration number", ylab = "Precision (%)",type = "o", lty = "solid", lwd = 2, col = "goldenrod4", ylim = c(25,70), pch=17, cex = 1.5, xaxt = "none", yaxt = "none")
axis(1, seq(0,8000, 1000),las=1, font=2,cex.axis=0.8)
axis(2, seq(0,70,5),las=2, font=2)

abline(h=seq(0,70,5), v=seq(0,20000, 1000), lty=3, col="lightgray")

abline(v = 2000, lty = "dotted", col = "seagreen")
abline(h = 44.93, lty = "dotdash", col = "seagreen")


plot(iterations,recall, xlab = "Iteration number", ylab = "Recall (%)",type = "o", lty = "solid", lwd = 2, col = "chocolate4", ylim = c(25,70), pch=18, cex = 1.5, xaxt = "none", yaxt = "none")
axis(1, seq(0,8000, 1000),las=1, font=2,cex.axis=0.8)
axis(2, seq(0,70,5),las=2, font=2)

abline(h=seq(0,70,5), v=seq(0,20000, 1000), lty=3, col="lightgray")

abline(v = 2000, lty = "dotted", col = "seagreen")
abline(h = 61.17, lty = "dotdash", col = "seagreen")


#png(filename=paste("C:/Users/mudar/Universidad de Alcala/JesusMudarra-MUII - Documentos/General/results/mAP_iteraciones_YOLOv4/prueba1/f1score.png",sep=""), width=5, height=5,units="in", res=300, pointsize=12)

plot(iterations,f1score, xlab = "Iteration number", ylab = "F1-score (%)",type = "o", lty = "solid", lwd = 2, col = "darkslategray", ylim = c(25,70), pch=15, cex = 1.5, xaxt = "none", yaxt = "none")
axis(1, seq(0,8000, 1000),las=1, font=2,cex.axis=0.8)
axis(2, seq(0,70,5),las=2, font=2)

abline(h=seq(0,70,5), v=seq(0,20000, 1000), lty=3, col="lightgray")

abline(v = 2000, lty = "dotted", col = "seagreen")
abline(h = 51.81, lty = "dotdash", col = "seagreen")

#dev.off()

```